# Generated by Django 4.2.8 on 2023-12-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_customer_address_alter_customer_name"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="заказчик",
        ),
    ]
