# Generated by Django 4.2.8 on 2023-12-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_alter_customer_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("marking", models.CharField(max_length=30)),
                ("affiliation", models.CharField(max_length=25)),
                ("profile", models.CharField(max_length=20)),
                ("height", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("thickness", models.IntegerField(null=True)),
                ("length", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "элемент",
            },
        ),
        migrations.CreateModel(
            name="ElementMaterialFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.element"
                    ),
                ),
            ],
            options={
                "db_table": "МатОгражЭлем",
            },
        ),
        migrations.CreateModel(
            name="Fence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marking", models.CharField(max_length=50)),
                ("grade", models.CharField(max_length=10)),
                ("subclass", models.CharField(max_length=20)),
                ("group", models.CharField(max_length=10)),
                ("subgroup", models.CharField(max_length=20)),
                ("typ", models.CharField(max_length=50)),
                ("retention_capacity", models.CharField(max_length=5)),
                ("impact_force", models.IntegerField(null=True)),
                ("height", models.FloatField(null=True)),
            ],
            options={
                "db_table": "ограждение",
            },
        ),
        migrations.CreateModel(
            name="Marking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marking", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("maker", models.CharField(max_length=50)),
                (
                    "fences_and_elements",
                    models.ManyToManyField(
                        related_name="fences_and_elements",
                        through="report.ElementMaterialFence",
                        to="report.fence",
                    ),
                ),
            ],
            options={
                "db_table": "материал",
            },
        ),
        migrations.AddField(
            model_name="elementmaterialfence",
            name="fence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="report.fence"
            ),
        ),
        migrations.AddField(
            model_name="elementmaterialfence",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="report.material"
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="materials_and_fences",
            field=models.ManyToManyField(
                related_name="elements_and_fences",
                through="report.ElementMaterialFence",
                to="report.material",
            ),
        ),
    ]
