# Generated by Django 4.2.8 on 2023-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_parameter_protocol_test_transport_testparameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fence",
            name="manufacturer",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="fence",
            name="step_rack",
            field=models.FloatField(null=True),
        ),
    ]
